name = "chika-act-rfq"
main = "workers/rfq-worker.js"
compatibility_date = "2026-06-16"

[vars]
ALLOWED_ORIGIN = "https://www.chikatech.com"
RFQ_TO_EMAIL = "yunimentalworking@gmail.com,blankk12321@gmail.com"
RFQ_FROM_EMAIL = "Chika ACT RFQ <rfq@chikatech.com>"

[[kv_namespaces]]
binding = "RFQ_KV"
id = "bf41ab14ed3144abbc49a743b61f5b6d"

# Required secret for email notification:
# wrangler secret put RESEND_API_KEY
